load("@py2deps//:requirements.bzl", py2_requirement="requirement")
load("@py3deps//:requirements.bzl", "requirement")

py_test(
    name='py2test',
    deps=[
      '//src/main/python/simple:simplelib',
    ],
    srcs=['py2test.py']
)